version: "3.8"

services:
    app:
      build:
        context: './'
        dockerfile: Dockerfile
      ports:
          - 8080:80
      volumes:
      - ./src:/var/www/html/
volumes:
  app:
          