version: "3.8"

services:
    app:
      build:
        context: '../'
        dockerfile: Dockerfile
      restart: always
      ports:
        - 8080:80
      volumes:
        - ../src:/var/www/html/
      networks:
        - secure
    mysql:
      image: mysql:8.0.28
      container_name: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: gestion
        MYSQL_USER: alvaro
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_PASSWORD: alvaro
      networks:
       - secure
      volumes:
        - ./database.sql:/docker-entrypoint-initdb.d/1.sql
volumes:
  app:
networks:
  secure:
    driver: bridge
          